name: CraftCore
version: ${version}
description: API for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.craftcore.spigot.Main
depend: [Multiverse-Core]
softdepend: [ProtocolLib,WorldGuard]
api-version: "1.14"