image: java:8-jdk

stages:
- validate
- build
- review
- deploy
- pages

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
- export GRADLE_USER_HOME=`pwd`/.gradle
- rm -f  .gradle/caches/modules-2/modules-2.lock
- rm -fr .gradle/caches/*/plugin-resolution/

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - target/

validate:
  stage: validate
  script:
  - ./gradlew check

build:
  stage: build
  script:
  - './gradlew clean'
  - './gradlew build -PciBranch=$CI_COMMIT_REF_NAME'
  artifacts:
    expire_in: 1 week
    paths:
    - target/*.jar

javadoc:
  stage: build
  script:
  - ./gradlew spigot:alljavadoc
  artifacts:
    expire_in: 1 week
    paths:
    - spigot/build/docs/javadoc/*
  only:
  - tags

pages:
  stage: pages
  script:
  - 'mkdir .public'
  - 'cp -r spigot/build/docs/javadoc/ public'
  - 'mv .public public'
  artifacts:
    paths:
    - public
  only:
  - tags

deploy:master:
  stage: deploy
  script:
  - './gradlew uploadArchives -PnexusUsername=$PACKAGES_USER -PnexusPassword=$PACKAGES_PASSWORD'
  only:
  - master@craftmania/crafteconomy
  when: manual

deploy:release:
  stage: deploy
  script:
  - './gradlew uploadArchives -PnexusUsername=$PACKAGES_USER -PnexusPassword=$PACKAGES_PASSWORD'
  only:
  - tags

codacy:
  stage: review
  script:
  - curl https://api.codacy.com/events/push/f22629ed146d4b719b97be48589f6ab3
  allow_failure: false