name: CraftCore
version: '2.12-beta.1'
description: Core API for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.craftcore.Main
depend:
  - Multiverse-Core
softdepend:
  - ProtocolLib
  - WorldGuard
loadbefore:
  - CMI
  - QuickShop
  - UltraMinions
api-version: "1.19"